<a href="https://colab.research.google.com/github/devlete/first_rep/blob/main/Projeto_de_1_ano.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/emendas/Despesas Resultado Primário (1).xlsx', sheet_name='BasePago')


colunas = {"GRUPOS DE DESPESA": [
          " DESPESAS CORRENTES  (EXCETO FONTES RPPS) (XVIII)"
        , "Pessoal e Encargos Sociais"
        , "Juros e Encargos da Dívida"
        , "Outras Despesas Correntes"
        , "DESPESAS PRIMÁRIAS CORRENTES (EXCETO FONTES RPPS) (XX) = (XVIII - XIX)"
        , "DESPESAS PRIMÁRIAS CORRENTES (COM FONTES RPPS) (XXI)"
        , "DESPESAS NÃO PRIMÁRIAS CORRENTES (COM FONTES RPPS) (XXII)"
        , "DESPESAS DE CAPITAL (XI)  (EXCETO FONTES RPPS) (XXIII)"
        , "Investimentos"
        , "Inversões Financeiras"
        , "Concessão de Empréstimos (4.5.90.66) (XXIV)"
        , "Aquisição de Título de Capital já integralizado (XXV)"
        , "Aquisição de Título de Crédito (XXVI)"
        , "Demais Inversões Financeiras (elem. 51,61,65,92)"
        , "Amortização da Dívida (XXVII) (*)"
        , "DESPESAS PRIMÁRIAS DE CAPITAL (EXCETO FONTES RPPS) (XXVIII) = [XXIII - (XXIV + XXV + XXVI + XXVII)]"
        , "RESERVA ORÇAMENTÁRIA PARA O RPPS (Ação Ftes Previdênciárias) (XXIX)"
        , "RESERVA DE CONTINGÊNCIA (XXX)"
        , "DESPESAS PRIMÁRIAS DE CAPITAL (COM FONTES RPPS) (XXXI)"
        , "DESPESAS NÃO PRIMÁRIAS DE CAPITAL (COM FONTES RPPS) (XXXII)"
        , "DESPESA PRIMÁRIA TOTAL (XXXIII) = (XX + XXI + XXVIII + XXIX + XXX+XXXI)"
        , "DESPESA PRIMÁRIA TOTAL (EXCETO FONTES RPPS) (XXXIV) = (XX + XXVIII + XXIX+XXX)"]}


df1 = pd.DataFrame(colunas)

#descobrir como renomear todas as colunas
#Como dar nome aos dataframes de forma mais eficiente
#colocar sempre a explicação do dataframe feito
#Como fazer os 3 filtros em um só
df_z1 = df.query('(`CLASSIFICAÇÃO DA CONTA DO PAGO` == "PAGO") & (`CATEGORIA  PAGO` == 31) & (`CLASSIFICAÇÃO DAS FONTES` == "Demais Fontes")')
df_z2 = df.query('(`CLASSIFICAÇÃO DA CONTA DO PAGO` == "PAGO") & (`CATEGORIA  PAGO` == 32) & (`CLASSIFICAÇÃO DAS FONTES` == "Demais Fontes")')


lista_z = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
Z1 = 0
for c in range(len(df_z1)):
  Z1 += df_z1.iat[c,8]
lista_z.insert(0,Z1)

Z2 = 0
for d in range(len(df_z2)):
  Z2 += df_z2.iat[d,8]
lista_z.insert(1,Z2)


df1['DESPESA PAGA 2022'] = lista_z

display(df1)

                                    GRUPOS DE DESPESA  DESPESA PAGA 2022
0    DESPESAS CORRENTES  (EXCETO FONTES RPPS) (XVIII)         1113359629
1                          Pessoal e Encargos Sociais           44901589
2                          Juros e Encargos da Dívida                  0
3                           Outras Despesas Correntes                  0
4   DESPESAS PRIMÁRIAS CORRENTES (EXCETO FONTES RP...                  0
5   DESPESAS PRIMÁRIAS CORRENTES (COM FONTES RPPS)...                  0
6   DESPESAS NÃO PRIMÁRIAS CORRENTES (COM FONTES R...                  0
7   DESPESAS DE CAPITAL (XI)  (EXCETO FONTES RPPS)...                  0
8                                       Investimentos                  0
9                               Inversões Financeiras                  0
10        Concessão de Empréstimos (4.5.90.66) (XXIV)                  0
11  Aquisição de Título de Capital já integralizad...                  0
12              Aquisição de Título de Crédito (XXVI)                  0
13   Demais Inversões Financeiras (elem. 51,61,65,92)                  0
14                  Amortização da Dívida (XXVII) (*)                  0
15  DESPESAS PRIMÁRIAS DE CAPITAL (EXCETO FONTES R...                  0
16  RESERVA ORÇAMENTÁRIA PARA O RPPS (Ação Ftes Pr...                  0
17                      RESERVA DE CONTINGÊNCIA (XXX)                  0
18  DESPESAS PRIMÁRIAS DE CAPITAL (COM FONTES RPPS...                  0
19  DESPESAS NÃO PRIMÁRIAS DE CAPITAL (COM FONTES ...                  0
20  DESPESA PRIMÁRIA TOTAL (XXXIII) = (XX + XXI + ...                  0
21  DESPESA PRIMÁRIA TOTAL (EXCETO FONTES RPPS) (X...                  0